### ISSUE TITLE
Derive the `_space_group_symop_operation_xyz` from `_cell_length_*` and `_cell_angle_*`.

### ISSUE THREAD

**Issue by hongyi-zhao** [jamesrhester/pycifrw#2]
Is it possible to derive the `_space_group_symop_operation_xyz` from `_cell_length_*` and `_cell_angle_*`? Say, the example shown [here](https://github.com/goodluck1982/SpaceGroupIrep/discussions/32#discussion-3876088):

Based on the following data:
```
_cell_length_a 3.3717
_cell_length_b 3.3717
_cell_length_c 5.3855(7)
_cell_angle_alpha 90.
_cell_angle_beta 90.
_cell_angle_gamma 120.
```

Can we derive the following data?
```
loop_
_space_group_symop_id
_space_group_symop_operation_xyz
1 '-x, -x+y, z+1/2'
2 'x-y, -y, z+1/2'
3 'y, x, z+1/2'
4 'x-y, x, z+1/2'
5 'y, -x+y, z+1/2'
6 '-x, -y, z+1/2'
7 'x, x-y, z'
8 '-x+y, y, z'
9 '-y, -x, z'
10 '-x+y, -x, z'
11 '-y, x-y, z'
12 'x, y, z'
loop_
```
Best,
Zhao

**Comment by jamesrhester** [comment]
Many space groups belong to the same lattice symmetry, so it is not possible to determine the space group from the cell parameters alone. I suggest reading International Tables for Crystallography Volume A for details. In any case this would be out of scope for PyCIFRW.
