### ISSUE TITLE
Non-ASCII characters not supported

### ISSUE THREAD

**Issue by CasperWA** [jamesrhester/pycifrw#4]
As laid out in emmo-repo/CIF-ontology#182 by @vaitkus, CIF2 now supports non-ASCII characters, which trip up the PyCIFRW parser(s).
See the referenced issue for an example.

**Comment by CasperWA** [comment]
I tried using `characterset="unicode"` and `standard="CIF2"` without any luck, unfortunately.

**Comment by jamesrhester** [comment]
I've fixed this in the latest commit to the development branch, and I'll bundle up a new release once I've figured out the new python packaging approach.

The problem was that nested blocks (e.g. dictionary definitions) had default characterset setting (ascii). Plain CIF2 data files are fine.

**Comment by jamesrhester** [comment]
Please try version 4.4.6. Source distribution and linux wheels provided.

**Comment by CasperWA** [comment]
I've tested v4.4.6 and it works beautifully!
I now get unicode characters nicely in the parsed CIF and dic files.

Just to show - here is a greek kappa that has gone all the way from dic file to Turtle ontology (see `κ-geometry diffractometer` in the circa center of the image):
![image](https://github.com/jamesrhester/pycifrw/assets/43357585/cba6024c-1207-4947-b2f0-b2f62ece3eb6)
