### ISSUE TITLE
SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by merkys** [jamesrhester/pycifrw#5]
The following line:
https://github.com/jamesrhester/pycifrw/blob/bd9b7ae234217bb5e10ebf204d2eeafd00611fa3/src/CifFile_module.nw#L561

emits a SyntaxWarning on Python 3.11:
```
CifFile/CifFile_module.py:356
  CifFile/CifFile_module.py:356: SyntaxWarning: "is not" with a literal. Did you mean "!="?
    if do_imports is not 'No':
```

**Comment by jamesrhester** [comment]
Yes, it should be '!='
